#include <stdint.h>

static const uint32_t /HOME/IURIE/PROJECTS/REDKITE/EXAMPLES/LABEL_WIDTH=100;
static const uint32_t /HOME/IURIE/PROJECTS/REDKITE/EXAMPLES/LABEL_HEIGHT=94;
static const uint8_t /HOME/IURIE/PROJECTS/REDKITE/EXAMPLES/LABEL_DATA[]={